### PR TITLE
remove auto-adding v to the etcd image version 

### PR DESCRIPTION
**Pull request by xmlking**
Please read https://github.com/coreos/etcd-operator/blob/master/CONTRIBUTING.md#contribution-flow

1. feat(tag): remove auto-adding v to the etcd image version
2. feat(policy): add option to configure HostNetwork and DNSPolicy

### CODE REVIEW

**Comment by xmlking** [comment]
@Marlinc  following are source for the above PR.
they are very important changes for my workplace environment where they have enabled Pod Security policies and CNI. I tested then @ workplace and works as expected, Hope you will merge PR.
https://github.com/coreos/etcd-operator/pull/2079
https://github.com/coreos/etcd-operator/pull/2094

**Comment by Wouter0100** [comment]
Thanks for the PR! We'll have a look.

**Comment by Wouter0100** [comment]
I've checked, could you please split the code in multiple merge requests? This merge request contains a lot of changes, mostly irrelevant to the MR itself. 

Thanks for the time and the effort.

**Comment by Marlinc** [comment]
Merged in 125c141793b8a19d6192cd503bac5b96084fa420

**Pull request closed without merging**
